FROM nikolaik/python-nodejs:python3.12-nodejs22

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    curl

SHELL [ "/bin/bash", "-o", "pipefail", "-c" ]

ENV RYE_HOME="/opt/rye"
ENV PATH="$RYE_HOME/shims:$PATH"

RUN curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" RYE_HOME=$RYE_HOME bash && \
    source "$RYE_HOME/env" && \
    rye config --set-bool behavior.global-python=true

