name: Python tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"] # 必要に応じてPythonのバージョンを指定

    steps:
    - uses: actions/checkout@v4
      # リポジトリのコードをチェックアウトしますs

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
      # 指定されたバージョンのPython環境をセットアップします

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Test with pytest
      run: |
        pytest
      # pytestコマンドを実行してテストを実施します
